config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'questions#index'
  resources :questions do
    collection do
      get 'index_q1'
      get 'index_q2'
      get 'index_q3'
      get 'index_q4'
      get 'index_q5'
      get 'index_q6'
      get 'index_q7'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  with_options presence: true do
    validates :question_index
    validates :score
    validates :user_id
  end
  belongs_to :user
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index; end

  def index_q1
    $add1 = AddQuestion.new(rand(1..9), rand(1..9))
    $add2 = AddQuestion.new(rand(1..9), rand(1..9))
    $add3 = AddQuestion.new(rand(1..9), rand(1..9))
    $add4 = AddQuestion.new(rand(1..9), rand(1..9))
    $add5 = AddQuestion.new(rand(1..9), rand(1..9))
  end

  def index_q2
    $add1 = AddQuestion.new(rand(10..99), rand(10..99))
    $add2 = AddQuestion.new(rand(10..99), rand(10..99))
    $add3 = AddQuestion.new(rand(10..99), rand(10..99))
    $add4 = AddQuestion.new(rand(10..99), rand(10..99))
    $add5 = AddQuestion.new(rand(10..99), rand(10..99))
  end

  def index_q3
    $add1 = AddQuestion.new(rand(100..999), rand(100..999))
    $add2 = AddQuestion.new(rand(100..999), rand(100..999))
    $add3 = AddQuestion.new(rand(100..999), rand(100..999))
    $add4 = AddQuestion.new(rand(100..999), rand(100..999))
    $add5 = AddQuestion.new(rand(100..999), rand(100..999))
  end

  def index_q4
    $sub1 = SubQuestion.new(rand(1..9), rand(1..9))
    $sub2 = SubQuestion.new(rand(1..9), rand(1..9))
    $sub3 = SubQuestion.new(rand(1..9), rand(1..9))
    $sub4 = SubQuestion.new(rand(1..9), rand(1..9))
    $sub5 = SubQuestion.new(rand(1..9), rand(1..9))
  end

  def index_q5
    $sub1 = SubQuestion.new(rand(10..99), rand(10..99))
    $sub2 = SubQuestion.new(rand(10..99), rand(10..99))
    $sub3 = SubQuestion.new(rand(10..99), rand(10..99))
    $sub4 = SubQuestion.new(rand(10..99), rand(10..99))
    $sub5 = SubQuestion.new(rand(10..99), rand(10..99))
  end

  def index_q6
    $sub1 = SubQuestion.new(rand(100..999), rand(100..999))
    $sub2 = SubQuestion.new(rand(100..999), rand(100..999))
    $sub3 = SubQuestion.new(rand(100..999), rand(100..999))
    $sub4 = SubQuestion.new(rand(100..999), rand(100..999))
    $sub5 = SubQuestion.new(rand(100..999), rand(100..999))
  end

  def index_q7
    $mul1 = MulQuestion.new(rand(1..9),rand(10..99))
    $mul2 = MulQuestion.new(rand(1..9),rand(10..99))
    $mul3 = MulQuestion.new(rand(1..9),rand(10..99))
    $mul4 = MulQuestion.new(rand(1..9),rand(10..99))
    $mul5 = MulQuestion.new(rand(1..9),rand(10..99))
  end

  def create
    @user_answer1 = params[:answer1]
    @user_answer2 = params[:answer2]
    @user_answer3 = params[:answer3]
    @user_answer4 = params[:answer4]
    @user_answer5 = params[:answer5]
    @count = 0
    if params[:q_id] == '1' || params[:q_id] == '2' || params[:q_id] == '3'
      @count += 1 if $add1.answer.to_s == @user_answer1
      @count += 1 if $add2.answer.to_s == @user_answer2
      @count += 1 if $add3.answer.to_s == @user_answer3
      @count += 1 if $add4.answer.to_s == @user_answer4
      @count += 1 if $add5.answer.to_s == @user_answer5
      @answer1 = $add1.answer
      @answer2 = $add2.answer
      @answer3 = $add3.answer
      @answer4 = $add4.answer
      @answer5 = $add5.answer
      @text1 = $add1.text
      @text2 = $add2.text
      @text3 = $add3.text
      @text4 = $add4.text
      @text5 = $add5.text
    elsif params[:q_id] == '4' || params[:q_id] == '5' || params[:q_id] == '6'
      @count += 1 if $sub1.answer.to_s == @user_answer1
      @count += 1 if $sub2.answer.to_s == @user_answer2
      @count += 1 if $sub3.answer.to_s == @user_answer3
      @count += 1 if $sub4.answer.to_s == @user_answer4
      @count += 1 if $sub5.answer.to_s == @user_answer5
      @answer1 = $sub1.answer
      @answer2 = $sub2.answer
      @answer3 = $sub3.answer
      @answer4 = $sub4.answer
      @answer5 = $sub5.answer
      @text1 = $sub1.text
      @text2 = $sub2.text
      @text3 = $sub3.text
      @text4 = $sub4.text
      @text5 = $sub5.text
    elsif params[:q_id] == '7' || params[:q_id] == '8' || params[:q_id] == '9'
      @count += 1 if $mul1.answer.to_s == @user_answer1
      @count += 1 if $mul2.answer.to_s == @user_answer2
      @count += 1 if $mul3.answer.to_s == @user_answer3
      @count += 1 if $mul4.answer.to_s == @user_answer4
      @count += 1 if $mul5.answer.to_s == @user_answer5
      @answer1 = $mul1.answer
      @answer2 = $mul2.answer
      @answer3 = $mul3.answer
      @answer4 = $mul4.answer
      @answer5 = $mul5.answer
      @text1 = $mul1.text
      @text2 = $mul2.text
      @text3 = $mul3.text
      @text4 = $mul4.text
      @text5 = $mul5.text
    end
    Question.create(question_index: params[:q_id], score: @count, user_id: current_user.id) if user_signed_in?
  end

  def show
    # 問１の解答データ取得-------------------------------------
    @user_questions1 = Question.where(user_id: current_user.id, question_index: 1)
    # 各得点の回数を配列に格納
    @user_questions1_scores = []
    # 点数の合計値
    sum_score = 0
    6.times do |t|
      @user_questions1_scores << @user_questions1.where(score: t).count
      # 得点x回数を合計値に追加
      sum_score += @user_questions1.where(score: t).count * t
    end
    # 合計値を全レコード数で除する
    @avg1 = if Question.where(user_id: current_user.id, question_index: 1).count == 0
              0
            else
              format('%.2f', sum_score / Question.where(user_id: current_user.id, question_index: 1).count.to_f)
            end

    @user_questions1_recent = Question.where(user_id: current_user.id, question_index: 1).order(:created_time).limit(5)

    # 問２の解答データ取得---------------------------------------
    @user_questions2 = Question.where(user_id: current_user.id, question_index: 2)
    # 各得点の回数を配列に格納
    @user_questions2_scores = []
    # 点数の合計値
    sum_score = 0
    6.times do |t|
      @user_questions2_scores << @user_questions2.where(score: t).count
      # 得点x回数を合計値に追加
      sum_score += @user_questions2.where(score: t).count * t
    end
    # 合計値を全レコード数で除する
    @avg2 = if Question.where(user_id: current_user.id, question_index: 1).count == 0
              0
            else
              format('%.2f', sum_score / Question.where(user_id: current_user.id, question_index: 2).count.to_f)
            end
    @user_questions2_recent = Question.where(user_id: current_user.id, question_index: 2).order(:created_time).limit(5)

    # 問３の解答データ取得------------------------------------------
    @user_questions3 = Question.where(user_id: current_user.id, question_index: 3)
    # 各得点の回数を配列に格納
    @user_questions3_scores = []
    # 点数の合計値
    sum_score = 0
    6.times do |t|
      @user_questions3_scores << @user_questions3.where(score: t).count
      # 得点x回数を合計値に追加
      sum_score += @user_questions3.where(score: t).count * t
    end
    # 合計値を全レコード数で除する
    @avg3 = if Question.where(user_id: current_user.id, question_index: 3).count == 0
              0
            else
              format('%.2f', sum_score / Question.where(user_id: current_user.id, question_index: 3).count.to_f)
            end
    @user_questions3_recent = Question.where(user_id: current_user.id, question_index: 3).order(:created_time).limit(5)

    # 問4の解答データ取得----------------------------------------------
    @user_questions4 = Question.where(user_id: current_user.id, question_index: 4)
    # 各得点の回数を配列に格納
    @user_questions4_scores = []
    # 点数の合計値
    sum_score = 0
    6.times do |t|
      @user_questions4_scores << @user_questions4.where(score: t).count
      # 得点x回数を合計値に追加
      sum_score += @user_questions4.where(score: t).count * t
    end
    # 合計値を全レコード数で除する
    @avg4 = if Question.where(user_id: current_user.id, question_index: 4).count == 0
              0
            else
              format('%.2f', sum_score / Question.where(user_id: current_user.id, question_index: 4).count.to_f)
            end
    @user_questions4_recent = Question.where(user_id: current_user.id, question_index: 4).order(:created_time).limit(5)

    # 問5の解答データ取得------------------------------------------------
    @user_questions5 = Question.where(user_id: current_user.id, question_index: 5)
    # 各得点の回数を配列に格納
    @user_questions5_scores = []
    # 点数の合計値
    sum_score = 0
    6.times do |t|
      @user_questions5_scores << @user_questions5.where(score: t).count
      # 得点x回数を合計値に追加
      sum_score += @user_questions5.where(score: t).count * t
    end
    # 合計値を全レコード数で除する
    @avg5 = if Question.where(user_id: current_user.id, question_index: 5).count == 0
              0
            else
              format('%.2f', sum_score / Question.where(user_id: current_user.id, question_index: 5).count.to_f)
            end
    @user_questions5_recent = Question.where(user_id: current_user.id, question_index: 5).order(:created_time).limit(5)

    # 問題6の解答データ取得----------------------------------------------
    @user_questions6 = Question.where(user_id: current_user.id, question_index: 6)
    # 各得点の回数を配列に格納
    @user_questions6_scores = []
    # 点数の合計値
    sum_score = 0
    6.times do |t|
      @user_questions6_scores << @user_questions6.where(score: t).count
      # 得点x回数を合計値に追加
      sum_score += @user_questions6.where(score: t).count * t
    end
    # 合計値を全レコード数で除する
    @avg6 = if Question.where(user_id: current_user.id, question_index: 4).count == 0
              0
            else
              format('%.2f', sum_score / Question.where(user_id: current_user.id, question_index: 6).count.to_f)
            end
    @user_questions6_recent = Question.where(user_id: current_user.id, question_index: 6).order(:created_time).limit(5)

    # 問題7の解答データ取得----------------------------------------------
    @user_questions7 = Question.where(user_id: current_user.id, question_index: 7)
    # 各得点の回数を配列に格納
    @user_questions7_scores = []
    # 点数の合計値
    sum_score = 0
    6.times do |t|
      @user_questions7_scores << @user_questions7.where(score: t).count
      # 得点x回数を合計値に追加
      sum_score += @user_questions7.where(score: t).count * t
    end
    # 合計値を全レコード数で除する
    @avg7 = if Question.where(user_id: current_user.id, question_index: 7).count == 0
              0
            else
              format('%.2f', sum_score / Question.where(user_id: current_user.id, question_index: 7).count.to_f)
            end

app/helpers/questions_helper.rb
module QuestionsHelper
end

class AddQuestion
  def initialize(a, b)
    @text = "#{a} + #{b}"
    @answer = a + b
  end

  attr_reader :text, :answer
end

class SubQuestion
  def initialize(a, b)
    if a >= b
      @text = "#{a} - #{b}"
      @answer = a - b
    else
      @text = "#{b} - #{a}"
      @answer = b - a
    end
  end
  attr_reader :text, :answer
end

class MulQuestion
  def initialize(a, b)
    @text = "#{a} X #{b}"
    @answer = a * b
  end
  attr_reader :text, :answer
end

app/views/questions/create.erb
<div class='index-title-box'>
    <div class='index-title'>
      <p>答え合わせ</p>
    </div>
</div>
<div class ='question-wrapper'>
  
    <div class='q'>
      <div class='q-title'>
      問１：　
      <% if "#{@answer1}" == @user_answer1 %>
      <div class='true'>
        <%= "正解" %>
      </div>      
      <% else %>
      <div class='false'>
        <%= "不正解"%>
      </div>
      <% end %>
      　
      <%= "#{@text1} = #{@answer1} " %>
      <%= "あなたの答え: #{@user_answer1}" %>
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問２：　
      <% if "#{@answer2}" == @user_answer2 %>
      <div class='true'>
        <%= "正解" %>
      </div>      
      <% else %>
      <div class='false'>
        <%= "不正解"%>
      </div>
      <% end %>
      　
      <%= "#{@text2} = #{@answer2} "  %>
      <%= "あなたの答え: #{@user_answer2}"%>
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問３：
      <% if "#{@answer3}" == @user_answer3 %>
      <div class='true'>
        <%= "正解" %>
      </div>      
      <% else %>
      <div class='false'>
        <%= "不正解"%>
      </div>
      <% end %>
      　
      <%= "#{@text3} = #{@answer3} "  %>
      <%= "あなたの答え: #{@user_answer3}"%>
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問４：
      <% if "#{@answer4}" == @user_answer4 %>
      <div class='true'>
        <%= "正解" %>
      </div>      
      <% else %>
      <div class='false'>
        <%= "不正解"%>
      </div>
      <% end %>
      　
      <%= "#{@text4} = #{@answer4} " %>
      <%= "あなたの答え: #{@user_answer4}"%>
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問５：　
      <% if "#{@answer5}" == @user_answer5 %>
      <div class='true'>
        <%= "正解" %>
      </div>      
      <% else %>
      <div class='false'>
        <%= "不正解"%>
      </div>
      <% end %>
      　
      <%= "#{@text5} = #{@answer5} "  %>
      <%= "あなたの答え: #{@user_answer5}"%>
      </div>
    </div> 
    <div class='q'>
      <div class='q-title'>
      <% if @count == 5%>
        <div class ='true'>
        おめでとう!!!　　
        </div>
      <% end %>
      あなたの得点は<%= @count %>/5点です
      </div>
    </div> 
    <div class='q'>
      <div class='q-title'>
      <%= link_to"トップページに戻る", root_path, class:'back'%>
      </div>
    </div>

    
</div>

app/views/questions/index.erb
<!doctype html>
<html class="no-js" lang="">

<head>
  <meta charset="utf-8">
  <title></title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta property="og:title" content="">
  <meta property="og:type" content="">
  <meta property="og:url" content="">
  <meta property="og:image" content="">

  <link rel="manifest" href="site.webmanifest">
  <link rel="apple-touch-icon" href="icon.png">
  <!-- Place favicon.ico in the root directory -->

  <%# <link rel="stylesheet" href="css/normalize.css"> %>
  <%# <link rel="stylesheet" href="css/main.css"> %>

  <meta name="theme-color" content="#fafafa">
</head>

<body>

  <!-- Add your site or application content here -->
  <div class='index-title-box'>
    <div class='index-title'>
      <p>宿題一覧</p>
    </div>
  </div>
  
  <div class ='question-wrapper'>
    <div class='q'>
      <div class='q-title'><%= link_to'問題1    1桁の足し算',index_q1_questions_path,class:"question-index" %></div>
    </div>
    <div class='q'>
      <div class='q-title'><%= link_to'問題2    2桁の足し算',index_q2_questions_path,class:"question-index" %></div>
    </div>
    <div class='q'>
      <div class='q-title'><%= link_to'問題3    3桁の足し算',index_q3_questions_path,class:"question-index" %></div>
    </div>
    <div class='q'>
      <div class='q-title'><%= link_to'問題4    1桁の引き算',index_q4_questions_path,class:"question-index" %></div>
    </div>
    <div class='q'>
      <div class='q-title'><%= link_to'問題5    2桁の引き算',index_q5_questions_path,class:"question-index" %></div>
    </div>
    <div class='q'>
      <div class='q-title'><%= link_to'問題6    3桁の引き算',index_q6_questions_path,class:"question-index"%></div>
    </div>
    <div class='q'>
      <div class='q-title'><%= link_to'問題7    1桁と2桁の掛け算',index_q7_questions_path,class:"question-index"%></div>
    </div>
    
  </div>
  
  

  
  <%# <script src="js/vendor/modernizr-3.11.2.min.js"></script>
  <script src="js/plugins.js"></script>
  <script src="js/main.js"></script> %>

  <!-- Google Analytics: change UA-XXXXX-Y to be your site's ID. -->
  <script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-XXXXX-Y', 'auto'); ga('set', 'anonymizeIp', true); ga('set', 'transport', 'beacon'); ga('send', 'pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async></script>
</body>

</html>

app/views/questions/index_q1.erb
<div class='index-title-box'>
    <div class='index-title'>
      <p>一桁の足し算(半角で入力して下さい)</p>
    </div>
</div>
<div class ='question-wrapper'>
  <%= form_with url: questions_path, local: true do |form| %>

    <div class='q'>
      <div class='q-title'>
      問１：　
      <%= $sum1.text %> =
      
      <%= form.text_field :answer1 ,class:'answer-form', placeholder:"入力欄"%>
     
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問２：　
      <%= $sum2.text %> =
      <%= form.text_field :answer2 ,class:'answer-form', placeholder:"入力欄"%>
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問３：　
      <%= $sum3.text%> =
      <%= form.text_field :answer3 ,class:'answer-form', placeholder:"入力欄" %>
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問４：　
      <%= $sum4.text %> =
      <%= form.text_field :answer4 ,class:'answer-form', placeholder:"入力欄" %>
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問５：　
      <%= $sum5.text %> =
      <%= form.text_field :answer5 ,class:'answer-form', placeholder:"入力欄" %>
      </div>
    </div> 
    
    <div class='q'>
      <div class='q-title'>
      <div class="answer-submit">
      <%= form.submit "解答する" ,class:"answer-button" %>
      </div>
    </div> 
    
      
    </div>
  <% end %>
</div>

app/views/questions/index_q2.erb
<div class='index-title-box'>
    <div class='index-title'>
      <p>2桁の足し算(半角で入力して下さい)</p>
    </div>
</div>
<div class ='question-wrapper'>
  <%= form_with url: questions_path(q_id:'2'), local: true do |form| %>

    <div class='q'>
      <div class='q-title'>
      問１：　
      <%= $add1.text %> =
      
      <%= form.text_field :answer1 ,class:'answer-form', placeholder:"入力欄"%>
     
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問２：　
      <%= $add2.text %> =
      <%= form.text_field :answer2 ,class:'answer-form', placeholder:"入力欄"%>
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問３：　
      <%= $add3.text%> =
      <%= form.text_field :answer3 ,class:'answer-form', placeholder:"入力欄" %>
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問４：　
      <%= $add4.text %> =
      <%= form.text_field :answer4 ,class:'answer-form', placeholder:"入力欄" %>
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問５：　
      <%= $add5.text %> =
      <%= form.text_field :answer5 ,class:'answer-form', placeholder:"入力欄" %>
      </div>
    </div> 
    
    <div class='q'>
      <div class='q-title'>
      <div class="answer-submit">
      <%= form.submit "解答する" ,class:"answer-button" %>
      </div>
    </div> 
    
      
    </div>
  <% end %>
</div>

app/views/questions/index_q3.erb
<div class='index-title-box'>
    <div class='index-title'>
      <p>3桁の足し算(半角で入力して下さい)</p>
    </div>
</div>
<div class ='question-wrapper'>
  <%= form_with url: questions_path(q_id:'3'), local: true do |form| %>

    <div class='q'>
      <div class='q-title'>
      問１：　
      <%= $add1.text %> =
      
      <%= form.text_field :answer1 ,class:'answer-form', placeholder:"入力欄"%>
     
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問２：　
      <%= $add2.text %> =
      <%= form.text_field :answer2 ,class:'answer-form', placeholder:"入力欄"%>
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問３：　
      <%= $add3.text%> =
      <%= form.text_field :answer3 ,class:'answer-form', placeholder:"入力欄" %>
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問４：　
      <%= $add4.text %> =
      <%= form.text_field :answer4 ,class:'answer-form', placeholder:"入力欄" %>
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問５：　
      <%= $add5.text %> =
      <%= form.text_field :answer5 ,class:'answer-form', placeholder:"入力欄" %>
      </div>
    </div> 
    
    <div class='q'>
      <div class='q-title'>
      <div class="answer-submit">
      <%= form.submit "解答する" ,class:"answer-button" %>
      </div>
    </div> 
    
      
    </div>
  <% end %>
</div>

app/views/questions/index_q4.erb
<div class='index-title-box'>
    <div class='index-title'>
      <p>1桁の引き算(半角で入力して下さい)</p>
    </div>
</div>
<div class ='question-wrapper'>
  <%= form_with url: questions_path(q_id: 4), local: true do |form| %>

    <div class='q'>
      <div class='q-title'>
      問１：　
      <%= $sub1.text %> =
      
      <%= form.text_field :answer1 ,class:'answer-form', placeholder:"入力欄"%>
     
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問２：　
      <%= $sub2.text %> =
      <%= form.text_field :answer2 ,class:'answer-form', placeholder:"入力欄"%>
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問３：　
      <%= $sub3.text%> =
      <%= form.text_field :answer3 ,class:'answer-form', placeholder:"入力欄" %>
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問４：　
      <%= $sub4.text %> =
      <%= form.text_field :answer4 ,class:'answer-form', placeholder:"入力欄" %>
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問５：　
      <%= $sub5.text %> =
      <%= form.text_field :answer5 ,class:'answer-form', placeholder:"入力欄" %>
      </div>
    </div> 
    
    <div class='q'>
      <div class='q-title'>
      <div class="answer-submit">
      <%= form.submit "解答する" ,class:"answer-button" %>
      </div>
    </div> 
    
      
    </div>
  <% end %>
</div>

app/views/questions/index_q5.erb
<div class='index-title-box'>
    <div class='index-title'>
      <p>２桁の引き算(半角で入力して下さい)</p>
    </div>
</div>
<div class ='question-wrapper'>
  <%= form_with url: questions_path(q_id:'5'), local: true do |form| %>

    <div class='q'>
      <div class='q-title'>
      問１：　
      <%= $sub1.text %> =
      
      <%= form.text_field :answer1 ,class:'answer-form', placeholder:"入力欄"%>
     
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問２：　
      <%= $sub2.text %> =
      <%= form.text_field :answer2 ,class:'answer-form', placeholder:"入力欄"%>
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問３：　
      <%= $sub3.text%> =
      <%= form.text_field :answer3 ,class:'answer-form', placeholder:"入力欄" %>
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問４：　
      <%= $sub4.text %> =
      <%= form.text_field :answer4 ,class:'answer-form', placeholder:"入力欄" %>
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問５：　
      <%= $sub5.text %> =
      <%= form.text_field :answer5 ,class:'answer-form', placeholder:"入力欄" %>
      </div>
    </div> 
    
    <div class='q'>
      <div class='q-title'>
      <div class="answer-submit">
      <%= form.submit "解答する" ,class:"answer-button" %>
      </div>
    </div> 
    
      
    </div>
  <% end %>
</div>

app/views/questions/index_q6.erb
<div class='index-title-box'>
    <div class='index-title'>
      <p>３桁の引き算(半角で入力して下さい)</p>
    </div>
</div>
<div class ='question-wrapper'>
  <%= form_with url: questions_path(q_id:'6'), local: true do |form| %>

    <div class='q'>
      <div class='q-title'>
      問１：　
      <%= $sub1.text %> =
      
      <%= form.text_field :answer1 ,class:'answer-form', placeholder:"入力欄"%>
     
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問２：　
      <%= $sub2.text %> =
      <%= form.text_field :answer2 ,class:'answer-form', placeholder:"入力欄"%>
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問３：　
      <%= $sub3.text%> =
      <%= form.text_field :answer3 ,class:'answer-form', placeholder:"入力欄" %>
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問４：　
      <%= $sub4.text %> =
      <%= form.text_field :answer4 ,class:'answer-form', placeholder:"入力欄" %>
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問５：　
      <%= $sub5.text %> =
      <%= form.text_field :answer5 ,class:'answer-form', placeholder:"入力欄" %>
      </div>
    </div> 
    
    <div class='q'>
      <div class='q-title'>
      <div class="answer-submit">
      <%= form.submit "解答する" ,class:"answer-button" %>
      </div>
    </div> 
    
      
    </div>
  <% end %>
</div>

app/views/questions/index_q7.erb
<div class='index-title-box'>
    <div class='index-title'>
      <p>1桁X2桁の引き算(半角で入力して下さい)</p>
    </div>
</div>
<div class ='question-wrapper'>
  <%= form_with url: questions_path(q_id:'7'), local: true do |form| %>

    <div class='q'>
      <div class='q-title'>
      問１：　
      <%= $mul1.text %> =
      
      <%= form.text_field :answer1 ,class:'answer-form', placeholder:"入力欄"%>
     
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問２：　
      <%= $mul2.text %> =
      <%= form.text_field :answer2 ,class:'answer-form', placeholder:"入力欄"%>
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問３：　
      <%= $mul3.text%> =
      <%= form.text_field :answer3 ,class:'answer-form', placeholder:"入力欄" %>
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問４：　
      <%= $mul4.text %> =
      <%= form.text_field :answer4 ,class:'answer-form', placeholder:"入力欄" %>
      </div>
    </div>
    <div class='q'>
      <div class='q-title'>
      問５：　
      <%= $mul5.text %> =
      <%= form.text_field :answer5 ,class:'answer-form', placeholder:"入力欄" %>
      </div>
    </div> 
    
    <div class='q'>
      <div class='q-title'>
      <div class="answer-submit">
      <%= form.submit "解答する" ,class:"answer-button" %>
      </div>
    </div> 
    
      
    </div>
  <% end %>
</div>